### ISSUE TITLE
Генки и Дюп мозгов, лмао.

### ISSUE THREAD

**Issue by OrangeMann** [animusdev/GreenBay#35]
![image](https://user-images.githubusercontent.com/10381296/27154904-6a094d6e-515f-11e7-9624-9c3bd812dbf8.png)
![image](https://user-images.githubusercontent.com/10381296/27154920-7d32a4b2-515f-11e7-8fdd-9011a65c494a.png)
Request for Help:: Zooopppaaa/(Kate Webb)(?) (PP) (VV) (SM) (JMP) (CA) (TAKE): если начать есть орган, то вылезет окошко типо есть или не есть, если нажать есть, то орган дюпает

**Comment by Redict** [comment]
Не смог повторить
