### ISSUE TITLE
нижнее бельё и ксенодауны

### ISSUE THREAD

**Issue by RandomColonist** [animusdev/GreenBay#38]
Насколько мне известно, Мэт временно выпилил расы из-за каких-то проблем с кровью путём закомменчивания пары строк в чарктер сетапе, то же самое он сделал с нижним бельём, которое отлично работает. Если с этим проблем нет - нужно откоментить выбор расы и белья в сетапе.

**Comment by OrangeMann** [comment]
Белье в сетапе есть.

**Comment by Redict** [comment]
https://i.gyazo.com/6d5fab26f5b1b42fa26cad8ad20a1612.png - белье.
Ксенодебилов мы убрали из-за проблем со спрайтами, как только починим спрайты так вернем.
