### ISSUE TITLE
Рева

### ISSUE THREAD

**Issue by RandomColonist** [animusdev/GreenBay#42]
Хуже генокрада может быть только рева. Рева, при которой ты являешься главой-лоялистом, а тебя в первые пять минут раунда сливает хоп-рева, вооружая своих анальных дружков в арсенале. Выпилите возможность быть ревой и лоялистами всему составу глав и сб.

**Comment by OrangeMann** [comment]
Убрал возможность выпадения ролек для глав и сб.
