### ISSUE TITLE
Рольки у которых есть скафандры должны форсить игроков за синтов быть хуманами

### ISSUE THREAD

**Issue by OrangeMann** [animusdev/GreenBay#43]
Нюка, Рейдеры, Ниндзя (вроде всё)

**Comment by RandomColonist** [comment]
Да не, на бее же есть штука, которая цепляется в слот костюма/на спину и охлаждает синта. Cooling unit называется. Её просто раздайте ролям, положив на мапу, и всё. То, что ты хочешь, справедливо только для ниндзи, пожалуй. А у рейдеров и нюки, если я правильно помню, уже есть такие холодильнички.

**Comment by Redict** [comment]
Оранж, распихай по карте эти юниты и на кораблике ниндзи тоже

**Comment by OrangeMann** [comment]
Распихал
