### ISSUE TITLE
Разнерфить станбатоны

### ISSUE THREAD

**Issue by OrangeMann** [animusdev/GreenBay#44]

**Comment by RandomColonist** [comment]
Тут станбатон работает не так примитивно, как на тг. Одного-двух ударов обычно не хватает, чтоб цель полностью вырубилась от шока. Бей больше - и будет тебе счастье.

**Comment by Redict** [comment]
Вообще, три удара должно хватить

**Comment by RandomColonist** [comment]
Сдвигать планку боя от "кто кого заробастит" к "кто кого первее застанит" - не есть разнерф. Можно чуть бафнуть батоны, ящитаю, чтоб станили быстрее, но не одним же ударом, иначе не будет возможности защититься от такого инстастана, не нося скафандр.

**Comment by Redict** [comment]
Нужно ли?

**Comment by OrangeMann** [comment]
Оставим этот вопрос самим игрокам.
