### ISSUE TITLE
Синтам можно выбить зубы

### ISSUE THREAD

**Issue by OrangeMann** [animusdev/GreenBay#45]

**Comment by Redict** [comment]
Насколько я знаю, у синтов не металлическая челюсть, но можно припилить им ее в limbs, но тогда нужны и дебаффы и баффы для них, например, если нет зубов, нельзя есть нормально, например, когда ты ешь, ты наносишь себе урон, а если у тебя синтозубы, тогда если тебе по ним бьют, то тот кто бьет получает урон, но при этом ты становишься уязвим для лазеров еще сильнее.

**Comment by Redict** [comment]
Пока закрою, но если захочется сделать, запилю.
