### ISSUE TITLE
Протолат

### ISSUE THREAD

**Issue by OrangeMann** [animusdev/GreenBay#54]
[Player PM] Alexix1989/(Aleksey Golubev)(?): Разобрать протолат нельзя. Пытаюсь вытащить детали ломом - ниху
[Player PM] Alexix1989/(Aleksey Golubev)(?): You can't load the Protolathe while it's opened.

**Comment by Redict** [comment]
[клик](https://i.gyazo.com/a3a5dce870fd98eaac27375ac485fab4.png).
Или пиздежь, или не репродуцируемая хуйня.
