### ISSUE TITLE
Маг

### ISSUE THREAD

**Issue by OrangeMann** [animusdev/GreenBay#58]
Request for Help:: GruesomeGrue/(Parrot (the Parrot (Rodney IX)))(?) (PP) (VV) (SM) (JMP) (CA) (TAKE): Офигеть. При повторном полимлрфе образуется ещё один визард.

**Comment by Redict** [comment]
Что такое полиморф?

**Comment by OrangeMann** [comment]
Заклинание такое, а че делает не уверен, мб превращение просто.

**Comment by OrangeMann** [comment]
https://github.com/animusdev/GreenBay/issues/62
