### ISSUE TITLE
Использование мезонок вызывает дичайшее потребление ЦП и лаги у клиента

### ISSUE THREAD

**Issue by EditorRUS** [animusdev/GreenBay#77]
Воспроизвести баг не могу, он возникает спонтанно, однако 3 раза подряд он появился когда я носил мезонки около капитанской каюты (в коридоре).

Лаги пропадают когда снимаешь мезонки и снова появляются когда надеваешь обратно.
Некоторое время лаги могут не идти.

Не знаю относительно других очков с цветным оверлеем.

**Comment by EditorRUS** [comment]
Смерджи с https://github.com/animusdev/GreenBay/issues/102

Этот баг прямо с ним связан: использование мезонок дает возможность видеть мокрый пол через стену. Баг был связан не с мезонками, а с тем, что ты видишь.

**Comment by OrangeMann** [comment]
Знаю
